import getStream from "get-stream";
import PDFDocument from "pdfkit";

export async function generatePdfBuffer({
  headerBrand,
  title,
  mode,
  question,
  answer,
  fullName,
  birthdate,
  birthTime,
  birthPlace,
  astrologySummary,
  numerologySummary,
  palmistrySummary,
  numerologyPack,
}) {
  const doc = new PDFDocument({ margin: 56 });
  const chunks = [];
  doc.on("data", (c) => chunks.push(c));
  doc.on("end", () => {});
  const line = (h) => doc.moveDown(h / 12);

  doc.font("Helvetica-Bold").fontSize(10).text(headerBrand, { align: "center" });
  doc.moveDown(0.4);
  doc.font("Helvetica-Bold").fontSize(20).text(title, { align: "center" });
  line(8);

  const h1 = (t) =>
    doc.font("Helvetica-Bold").fontSize(14).text(t, { underline: true }).moveDown(0.3);

  if (question) {
    h1("Question");
    doc.font("Helvetica").fontSize(12).text(question);
    line(6);
  }

  h1("Answer");
  doc.font("Helvetica").fontSize(12).text(answer || "—");
  line(6);

  if (mode === "personal") {
    h1("Astrology");
    doc.text(astrologySummary || "—");
    line(6);
    h1("Numerology");
    doc.text(numerologySummary || "—");
    if (numerologyPack) {
      Object.entries(numerologyPack).forEach(([k, v]) =>
        doc.text(`${k[0].toUpperCase() + k.slice(1)} — ${v}`)
      );
    }
    line(6);
    h1("Palmistry");
    doc.text(palmistrySummary || "—");
  }

  line(8);
  doc.fontSize(9).fillColor("#555").text("Generated by Melodies Web", { align: "center" });
  doc.end();
  return await getStream.buffer(doc);
}
