// /api/utils/generatePdf.js
import PDFDocument from "pdfkit";
import getStream from "get-stream";

export async function generatePdfBuffer({
  fullName,
  birthdate,
  birthTime,
  birthPlace,
  reading = {},
}) {
  const doc = new PDFDocument({ margin: 50 });
  const chunks = [];

  doc.on("data", (chunk) => chunks.push(chunk));
  doc.on("end", () => console.log("✅ PDF generation complete"));

  // Title
  doc
    .fontSize(22)
    .fillColor("#4B0082")
    .text("🔮 Spiritual Report", { align: "center" })
    .moveDown(1);

  // Personal Info Section
  doc
    .fontSize(14)
    .fillColor("#000")
    .text(`👤 Name: ${fullName}`)
    .moveDown(0.2)
    .text(`📅 Birth Date: ${birthdate}`)
    .moveDown(0.2)
    .text(`⏰ Birth Time: ${birthTime || "Unknown"}`)
    .moveDown(0.2)
    .text(`🌍 Birth Place: ${birthPlace}`)
    .moveDown(1.5);

  // Section Divider
  const divider = (title) => {
    doc
      .fontSize(16)
      .fillColor("#4B0082")
      .text(title, { underline: true })
      .moveDown(0.5);
  };

  // Astrology Section
  divider("🌟 Astrology Insights");
  doc
    .fontSize(12)
    .fillColor("#333")
    .text(reading.astrology || "No astrology insights available.")
    .moveDown(1);

  // Numerology Section
  divider("🔢 Numerology Insights");
  doc
    .fontSize(12)
    .fillColor("#333")
    .text(reading.numerology || "No numerology insights available.")
    .moveDown(1);

  // Palmistry Section
  divider("✋ Palmistry Insights");
  doc
    .fontSize(12)
    .fillColor("#333")
    .text(reading.palmistry || "No palmistry insights available.")
    .moveDown(2);

  // Footer
  doc
    .fontSize(10)
    .fillColor("#888")
    .text(
      "✨ This personalized report was generated by Hazcam Spiritual Systems using astrological, numerological, and palmistry insights.",
      { align: "center" }
    );

  doc.end();
  return await getStream.buffer(doc);
}
