// /api/utils/generatePdf.js
// /api/utils/generatePdf.js
// /api/utils/generatePdf.js

import getStream from "get-stream";

let PDFDocument;
try {
  PDFDocument = (await import("pdfkit")).default;
} catch (err) {
  console.error("❌ Failed to load PDFKit:", err);
  throw err;
}

function drawSectionHeading(doc, title) {
  const pageBottom = doc.page.height - doc.page.margins.bottom;
  if (doc.y + 40 > pageBottom) doc.addPage();
  doc.moveDown(0.4).fontSize(16).fillColor("#4B0082").text(title, { underline: true }).moveDown(0.6);
}

function drawParagraph(doc, text, size = 12, color = "#333") {
  const pageBottom = doc.page.height - doc.page.margins.bottom;
  if (doc.y + 40 > pageBottom) doc.addPage();
  doc.fontSize(size).fillColor(color).text(text || "—", { lineGap: 6 }).moveDown(0.8);
}

export async function generatePdfBuffer({
  fullName,
  birthdate,
  birthTime,
  birthPlace,
  question,
  answer,
  astrology,
  numerology,
  palmistry,
  astroDetails = {},
  numDetails = {},
  palmDetails = {},
}) {
  const doc = new PDFDocument({ margin: 50 });
  const chunks = [];
  doc.on("data", (c) => chunks.push(c));
  doc.on("end", () => console.log("✅ PDF generated."));

  // Header
  doc.fontSize(22).fillColor("#4B0082").text("Personal Spiritual Report", { align: "center" }).moveDown(1);
  doc.fontSize(12).fillColor("#111");
  doc.text(`Name: ${fullName}`).text(`Birth Date: ${birthdate}`).text(`Birth Time: ${birthTime}`).text(`Birth Place: ${birthPlace}`).text(`Question: ${question}`).moveDown(1);

  drawSectionHeading(doc, "Answer to Your Question");
  drawParagraph(doc, answer);

  // Astrology
  drawSectionHeading(doc, "Astrology");
  drawParagraph(doc, astrology);
  Object.entries(astroDetails || {}).forEach(([k, v]) => {
    if (k !== "summary") {
      doc.fontSize(13).fillColor("#4B0082").text(k).fillColor("#333").fontSize(12).text(v, { lineGap: 6 }).moveDown(0.4);
    }
  });

  // Numerology
  drawSectionHeading(doc, "Numerology");
  drawParagraph(doc, numerology);
  ["Life Path", "Expression", "Personality", "Soul Urge", "Maturity"].forEach((key) => {
    const entry = numDetails[key];
    if (entry) {
      doc.fontSize(13).fillColor("#4B0082").text(`${key} — ${entry.number || ""}`).fillColor("#333").fontSize(12).text(entry.meaning || "", { lineGap: 6 }).moveDown(0.4);
    }
  });

  // Palmistry
  drawSectionHeading(doc, "Palmistry");
  drawParagraph(doc, palmistry);
  Object.entries(palmDetails || {}).forEach(([k, v]) => {
    if (k !== "summary") {
      doc.fontSize(13).fillColor("#4B0082").text(k).fillColor("#333").fontSize(12).text(v, { lineGap: 6 }).moveDown(0.4);
    }
  });

  doc.moveDown(1).fontSize(10).fillColor("#777").text("Generated by Hazcam Spiritual Systems", { align: "center" });
  doc.end();
  return await getStream.buffer(doc);
}
